"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const tournamentController_1 = require("../controllers/tournamentController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.get("/", authMiddleware_1.requireAuth, tournamentController_1.getTournaments);
router.post("/", authMiddleware_1.requireAuth, tournamentController_1.createTournament);
router.get("/:tournamentId", authMiddleware_1.requireAuth, tournamentController_1.getTournament);
router.patch("/:tournamentId", authMiddleware_1.requireAuth, tournamentController_1.updateTournament);
router.put("/:tournamentId", authMiddleware_1.requireAuth, tournamentController_1.updateTournament);
router.delete("/:tournamentId", authMiddleware_1.requireAuth, tournamentController_1.deleteTournament);
router.get("/:tournamentId/teams", authMiddleware_1.requireAuth, tournamentController_1.getTournamentTeams);
router.post("/:tournamentId/teams", authMiddleware_1.requireAuth, tournamentController_1.createTournamentTeam);
router.patch("/:tournamentId/teams/:teamId", authMiddleware_1.requireAuth, tournamentController_1.updateTournamentTeam);
router.put("/:tournamentId/teams/:teamId", authMiddleware_1.requireAuth, tournamentController_1.updateTournamentTeam);
router.put("/:tournamentId/teams/:teamId/players", authMiddleware_1.requireAuth, tournamentController_1.updateTournamentTeamPlayers);
router.patch("/:tournamentId/teams/:teamId/statistics", authMiddleware_1.requireAuth, tournamentController_1.updateTournamentTeamStatistics);
router.delete("/:tournamentId/teams/:teamId", authMiddleware_1.requireAuth, tournamentController_1.deleteTournamentTeam);
router.post("/:tournamentId/statistics/recalculate", authMiddleware_1.requireAuth, tournamentController_1.recalculateTournamentTeamStatistics);
router.post("/:tournamentId/statistics/sync", authMiddleware_1.requireAuth, tournamentController_1.recalculateTournamentTeamStatistics);
router.post("/:tournamentId/points-table/sync", authMiddleware_1.requireAuth, tournamentController_1.recalculateTournamentTeamStatistics);
router.get("/:tournamentId/matches", authMiddleware_1.requireAuth, tournamentController_1.getTournamentMatchesList);
router.post("/:tournamentId/matches/start", authMiddleware_1.requireAuth, tournamentController_1.startTournamentMatch);
router.post("/:tournamentId/matches/complete", authMiddleware_1.requireAuth, tournamentController_1.completeTournamentMatch);
router.post("/:tournamentId/matches/:matchId/complete", authMiddleware_1.requireAuth, tournamentController_1.completeTournamentMatch);
router.patch("/:tournamentId/matches/:matchId/fix", authMiddleware_1.requireAuth, tournamentController_1.completeTournamentMatch);
router.post("/:tournamentId/matches/:matchId/fix", authMiddleware_1.requireAuth, tournamentController_1.completeTournamentMatch);
exports.default = router;
//# sourceMappingURL=tournamentRoutes.js.map