export const SocketIOEvents = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  MESSAGE: "message",
  ERROR: "error",
  GAME_STARTED: "GAME_STARTED",
  GAME_SCORE_UPDATED: "GAME_SCORE_UPDATED",
  LIVE_UPDATES: "LIVE_UPDATES",
  HOME_PAGE_VIEW: "HOME_PAGE_VIEW",
};
export const SocketIOClientEvents = {
  GAME_JOIN: "GAME_JOIN",
  GAME_END: "GAME_END",
  GAME_SCORE_UPDATE: "GAME_SCORE_UPDATE",
  LIVE_UPDATES: "LIVE_UPDATES",
  HOME_PAGE_VIEW: "HOME_PAGE_VIEW",
};
